version: "3"

services:
  webservice:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        # Update the VARIANT arg to pick a Java version: 11, 15
        VARIANT: 11
        # Options
        INSTALL_MAVEN: "false"
        INSTALL_GRADLE: "false"
        INSTALL_NODE: "false"
        NODE_VERSION": "lts/*"
    command: sleep infinity
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/workspace
      - ./m2-docker:/home/vscode/.m2

  mongo:
    image: mongo:4.2.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:?Required}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?Required}
      MONGO_INITDB_DATABASE: security
    volumes:
      - ./mongodump:/mongodump
      - ./mongo_migration:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:?Required}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:?Required}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST:?Required}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:?Required}
    ports:
      - "10000:8081"
    depends_on:
      - mongo
