version: "3"

services:
  webservice:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    env_file: .env
    environment:
      APP_PORT: 5000
      APP_HOST: 0.0.0.0
    command: sleep infinity
    ports:
      - "5000:5000"
    volumes:
      - ./:/workspace
      - ./m2-docker:/home/vscode/.m2

  mongo:
    image: mongo:4.2.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:?Required}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?Required}
    volumes:
      - ./mongodump:/mongodump

  mongotest:
    image: mongo:4.2.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TEST_MONGO_USERNAME:?Required}
      MONGO_INITDB_ROOT_PASSWORD: ${TEST_MONGO_PASSWORD:?Required}

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "10000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:?Required}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:?Required}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST:?Required}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:?Required}
    depends_on:
      - mongo
