@baseUrl = http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/security/graphql
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaXNzIjoiYW5hc2RpZGkuZGV2IiwiaWF0IjoxNTE2MjM5MDIyfQ.fzLgJlshK6aJ135zy_fFMigGJVdN-myDMWOrTiah3zY
// signature=secret, issuer=anasdidi.dev

// @name ping

POST {{baseUrl}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "query": "query($value: String!) { ping(value: $value) { isSuccess testValue } }",
  "variables": {
    "value": "Hello world!"
  }
}

###

// @name getUserList
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "query": "query ($format: String) { getUserList { id username fullName email lastModifiedBy { id } lastModifiedDate(format: $format) version telegramId permissions } }",
  "variables": {
    "format": "yyyy-MM-dd HH:mm:ss"
  }
}

###

// @name getUserById
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "query": "query ($id: String!, $format: String) { getUserById(id: $id) { id username fullName email lastModifiedBy { id } lastModifiedDate(format: $format) version telegramId permissions } }",
  "variables": {
    "id": "5ffee46fb0cf4605a498acc4",
    "format": "yyyy-MM-dd HH:mm:ss"
  }
}

###

// @name getUserByUsername
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "query": "query ($username: String!, $format: String) { getUserByUsername(username: $username) { id username fullName email lastModifiedBy { id } lastModifiedDate(format: $format) version telegramId permissions } }",
  "variables": {
    "username": "superadmin",
    "format": "yyyy-MM-dd HH:mm:ss"
  }
}
