@port = 5000
@host = localhost
@hostname = {{host}}:{{port}}
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaXNzIjoiYW5hc2RpZGkuZGV2IiwiaWF0IjoxNTE2MjM5MDIyfQ.fzLgJlshK6aJ135zy_fFMigGJVdN-myDMWOrTiah3zY
// signature=secret, issuer=anasdidi.dev

// @name getUserList
POST http://{{hostname}}/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "query": "query { getUserList { id username fullName version } }",
  "variables": null
}

###

// @name getUserById
POST http://{{hostname}}/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "query": "query ($id: String!) { getUserById(id: $id) { id username version } }",
  "variables": {
    "id": "E300DC218B164E988533752B6562A4EC"
  }
}

###

// @name getUserByUsername
POST http://{{hostname}}/graphql
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "query": "query ($username: String!) { getUserByUsername(username: $username) { id username version } }",
  "variables": {
    "username": "superadmin"
  }
}
