@host = localhost
@port = 5000
@hostname = {{host}}:{{port}}
@uri = /security/api/jwt

// @name login
POST http://{{hostname}}{{uri}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "anas.didi95",
  "password": "08071aN@"
}

###

@refreshId = {{login.response.body.$.data.refreshId}}

// @name refresh
POST http://{{hostname}}{{uri}}/refresh
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.data.accessToken}}

{
  "id": "{{refreshId}}"
}
