@baseUrl = http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/security/api/jwt

// @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/json

{
  "username": "superadmin",
  "password": "password"
}

###

@accessToken = {{login.response.body.$.data.accessToken}}
@refreshToken = {{login.response.body.$.data.refreshToken}}

// @name refresh
POST {{baseUrl}}/refresh
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "refreshToken": "{{refreshToken}}"
}

###

@accessToken = {{login.response.body.$.data.accessToken}}

GET {{baseUrl}}/check
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

@accessToken = {{login.response.body.$.data.accessToken}}

GET {{baseUrl}}/logout
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}
