@host = localhost
@port = 5000
@hostname = {{host}}:{{port}}


// @name createContent
POST http://{{hostname}}/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "superadmin2",
  "password": "password",
  "fullName": "superadmin",
  "email": "anas.didi95@gmail.com"
}

###

@userId = {{createContent.response.body.$.data.id}}

// @name updateContent
PUT http://{{hostname}}/api/users/{{userId}}
Accept: application/json
Content-Type: application/json

{
  "username": "superadmin",
  "password": "password",
  "fullName": "anas",
  "email": "anas.didi95@gmail.com1",
  "version": 0
}

###

// @name deleteContent
DELETE http://{{hostname}}/api/users/{{userId}}
Accept: application/json
Content-Type: application/json

{
  "version": 1
}
