@baseUrl = http://{{$processEnv APP_HOST}}:{{$processEnv APP_PORT}}/security/api/user
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaXNzIjoiYW5hc2RpZGkuZGV2IiwiaWF0IjoxNTE2MjM5MDIyfQ.fzLgJlshK6aJ135zy_fFMigGJVdN-myDMWOrTiah3zY
// signature=secret, issuer=anasdidi.dev

// @name createContent
POST {{baseUrl}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "superadmin",
  "password": "password",
  "fullName": "superadmin",
  "email": "anas.didi95@gmail.com"
}

###

@userId = {{createContent.response.body.$.data.id}}

// @name updateContent
PUT {{baseUrl}}/{{userId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "fullName": "anas juwaidi 123",
  "email": "anas.didi95@gmail.com1",
  "version": 0
}

###

// @name deleteContent
DELETE {{baseUrl}}/{{userId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "version": 0
}
