@host = localhost
@port = 5000
@hostname = {{host}}:{{port}}

### Sample
POST http://{{hostname}}/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "superadmin",
  "password": "password",
  "fullName": "superadmin",
  "email": "anas.didi95@gmail.com"
}
