@host = localhost
@port = 5000
@hostname = {{host}}:{{port}}
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaXNzIjoiYW5hc2RpZGkuZGV2IiwiaWF0IjoxNTE2MjM5MDIyfQ.fzLgJlshK6aJ135zy_fFMigGJVdN-myDMWOrTiah3zY
// signature=secret, issuer=anasdidi.dev

// @name createContent
POST http://{{hostname}}/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "superadmin",
  "password": "password",
  "fullName": "superadmin",
  "email": "anas.didi95@gmail.com"
}

###

@userId = {{createContent.response.body.$.data.id}}

// @name updateContent
PUT http://{{hostname}}/api/user/{{userId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "superadmin",
  "password": "password",
  "fullName": "anas juwaidi",
  "email": "anas.didi95@gmail.com1",
  "version": 1
}

###

// @name deleteContent
DELETE http://{{hostname}}/api/user/{{userId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "version": 2
}
